version: '3'

services:
  train:
    image: hsh0322/las-pytorch
    volumes:
      - ./:/opt/project
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    command:
       python3 train_timit.py config/las_timit_mel_spectrogram_120_config.yaml

  tensorboard:
    image: hsh0322/las-pytorch
    volumes:
      - ./:/opt/project
    ports:
      - "6006:6006"
    command: tensorboard --logdir=log/las_timit --port=6006 --host=0.0.0.0